plt.figure(figsize=(10, 5))
plt.plot(data_sizes, times, marker='o', label='Serial')
plt.plot(data_sizes, times_parallel, marker='o', label='Parallel')
plt.xlabel('Data Size')
plt.ylabel('Time (s)')
plt.title('Comparison of Serial and Parallel Quicksort Performance')
plt.legend()
plt.grid(True)
plt.show()
